sudo: false
language: node_js
node_js:
  - 10
install:
  - npm install
  - npm run-script build

addons:
  code_climate:
    repo_token: "$CODECLIMATE_TOKEN"

deploy:
  provider: npm
  skip_cleanup: true
  email: "$NPM_EMAIL_ADDRESS"
  api_key: "$NPM_AUTH_TOKEN"
  on:
    tags: true

after_script:
	- codeclimate-test-reporter < ./coverage/lcov.info
