sudo: false
language: node_js
node_js:
  - 10

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - npm install
  - npm run-script build

addons:
  code_climate:
    repo_token: "$CODECLIMATE_TOKEN"

deploy:
  provider: npm
  skip_cleanup: true
  email: "$NPM_EMAIL_ADDRESS"
  api_key: "$NPM_AUTH_TOKEN"
  on:
    tags: true

after_script:
  - ./cc-test-reporter after-build -t lcov --exit-code $TRAVIS_TEST_RESULT
